### ISSUE TITLE
Clean up the code and get Scrutinizer rating up a bit

### ISSUE THREAD

**Issue by willyb321** [willyb321/elite-journal#15]
The main problem with the code is its complexity rating. Have a look at the Scrutinizer report if you want to see. https://scrutinizer-ci.com/g/willyb321/elite-journal/?branch=master

**Comment by abhanshgiri21** [comment]
hey, i am new to github and i wanted to do some open source.
can you tell me how can i help on this one?

**Comment by abdulamite** [comment]
I am interested in getting involved in open source community, could I possibly help out with this project?
