### ISSUE TITLE
Publishing secrets

### ISSUE THREAD

**Issue by sporebat** [willyb321/elite-journal#25]
Putting authentication tokens in configuration files and publishing them to the world can turn out badly. Revoke the tokens, then find a way to store the secrets in the environment or unpublished (`.gitignore`) file.

**Comment by sporebat** [comment]
Or, did you already [do this](https://www.appveyor.com/docs/how-to/git-push/#configuring-build-secure-variable-with-access-token)? If those are encrypted, well played, I guess.

**Comment by willyb321** [comment]
Yes, I did in fact already encrypt them.(assuming you are talking about appveyor)

**Comment by sporebat** [comment]
Woot.
